version: '3.8'

services:
  webscraper:
    build: .
    container_name: ronak-webscraper
    ports:
      - "3000:3000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx2g -Xms1g -XX:+UseG1GC
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
